services:
  - type: web
    name: ecommerce-app-hv1l
    env: node
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ecommerce_app_hv1l
          property: connectionString
      - key: NODE_ENV
        value: production
    buildFilter:
      paths:
        - prisma/**
        - src/**
        - package.json
        - tsconfig.json